import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import MiniKitRootProvider from './providers/minikit-provider';
import AppTRPCProvider from './providers/trpc-provider';
import ErudaProvider from './providers/eruda-provider';
import AppI18nProvider from './providers/i18n-provider';
import DevMenu from '~/components/DevMenu';
import AppShell from './providers/app-shell';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppTRPCProvider>
          <ErudaProvider>
            <AppI18nProvider>
              <MiniKitRootProvider>
                <AppShell>
                  {children}
                  <DevMenu />
                </AppShell>
              </MiniKitRootProvider>
            </AppI18nProvider>
          </ErudaProvider>
        </AppTRPCProvider>
      </body>
    </html>
  );
}
